# Changing the data

There may be several reasons and needs to change the data.
<ul>
    <li>Changing names of variables, i.e. columns.</li>    
    <li>Removing useless variables. </li>
    <li>Replacing index with values of a variable. </li>
    <li>Correcting incorrect values.</li>
    <li>Calculating new variables from existing ones.</li>
    <li>Removing rows with missing values. (In descriptive and diagnostic analysis this is usually not necessary, except in calculating statistical significance of correlation coefficient.) </li>
</ul>

In [2]:
### First import the basic library of data analysis.

import pandas as pd

### Open the data in a dataframe.

df = pd.read_excel('http://myy.haaga-helia.fi/~menetelmat/Data-analytiikka/Teaching/data1_en.xlsx')

### We want to view all the rows of the data.

pd.options.display.max_rows = None

df

,number,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties,occu_health,timeshare,gym,massage
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN
3,4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN
4,5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN
5,6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN
6,7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN
7,8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN
8,9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN
9,10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN
10,11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN
11,12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0
12,13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN
13,14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN
14,15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN
15,16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0
16,17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN
17,18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN
18,19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0
19,20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0
20,21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN
21,22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN
22,23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN
23,24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN
24,25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN
25,26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0
26,27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0
27,28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0
28,29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN
29,30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN
30,31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0
31,32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN
32,33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN
33,34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0
34,35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0
35,36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN
36,37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0
37,38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN
38,39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN
39,40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN
40,41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN
41,42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN
42,43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN
43,44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0
44,45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0
45,46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0
46,47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN
47,48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN
48,49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN
49,50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN
50,51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN
51,52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN
52,53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN
53,54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN
54,55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0
55,56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0
56,57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0
57,58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0
58,59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN
59,60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN
60,61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN
61,62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN
62,63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN
63,64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0
64,65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0
65,66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN
66,67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0
67,68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN
68,69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN
69,70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0
70,71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN
71,72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN
72,73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN
73,74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN
74,75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN
75,76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN
76,77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN
77,78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN
78,79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN
79,80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN
80,81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN
81,82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN

## Changing variable names

In [3]:
### Before changing names of variables, you may wish to view current names first.

df.columns

Index(['number', 'sex', 'age', 'family', 'education', 'empl_years', 'salary',
       'management', 'colleagues', 'environment', 'salary_level', 'duties',
       'occu_health', 'timeshare', 'gym', 'massage'],
      dtype='object')

In [4]:
### Names of variables can be copied from the list above and changes can be made.

df.columns = ['number', 'sex', 'age', 'family', 'education', 'empl_years', 'salary',
       'sat_management', 'sat_colleagues', 'sat_environment', 'sat_salary', 'sat_duties',
       'occu_health', 'timeshare', 'gym', 'massage']

In [5]:
### Let us check that the result is what we wish for

df.columns

Index(['number', 'sex', 'age', 'family', 'education', 'empl_years', 'salary',
       'sat_management', 'sat_colleagues', 'sat_environment', 'sat_salary',
       'sat_duties', 'occu_health', 'timeshare', 'gym', 'massage'],
      dtype='object')

In [7]:
### Variable names can also be changed using the command rename()
### Note that here Python's data structure dictionary is used. Dictionary's content is between curly brackets { }.

df = df.rename(columns = {'sat_management': 'management', 'sat_colleagues': 'colleagues', 'sat_environment': 'environment', 'sat_salary': 'salary_level', 'sat_duties': 'duties'})

In [8]:
### Let us again check that the result is what we wish for

df.columns

Index(['number', 'sex', 'age', 'family', 'education', 'empl_years', 'salary',
       'management', 'colleagues', 'environment', 'salary_level', 'duties',
       'occu_health', 'timeshare', 'gym', 'massage'],
      dtype='object')

## Removing variables

In [9]:
### Using the command drop() variables can be removed
### By default drop() removes rows (axis = 0) nut in the next example we want to remove columns (axis = 1)

df1 = df.drop(['occu_health', 'timeshare', 'gym', 'massage'], axis = 1)

### View the result
df1

,number,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3
3,4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3
4,5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2
5,6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4
6,7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2
7,8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3
8,9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4
9,10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1
10,11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3
11,12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2
12,13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4
13,14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3
14,15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4
15,16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3
16,17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5
17,18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1
18,19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4
19,20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2
20,21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4
21,22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4
22,23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4
23,24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5
24,25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4
25,26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3
26,27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3
27,28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4
28,29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4
29,30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2
30,31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2
31,32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4
32,33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4
33,34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2
34,35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3
35,36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3
36,37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5
37,38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4
38,39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4
39,40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3
40,41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3
41,42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2
42,43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4
43,44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3
44,45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4
45,46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3
46,47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3
47,48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3
48,49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5
49,50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3
50,51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5
51,52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5
52,53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1
53,54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2
54,55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3
55,56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3
56,57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5
57,58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2
58,59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3
59,60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3
60,61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2
61,62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3
62,63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3
63,64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3
64,65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4
65,66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5
66,67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2
67,68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4
68,69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4
69,70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2
70,71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4
71,72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4
72,73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4
73,74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3
74,75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1
75,76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1
76,77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2
77,78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4
78,79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2
79,80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3
80,81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3
81,82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4

## Index

Index of a dataframe is the left-most column. By default an index is a sequence of running numbers which start at zero. Another variable can be reassigned to be the index.

In [10]:
### Reassigning a variable to become the index (the left-most boldface column)

df = df.set_index('number')
df

,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties,occu_health,timeshare,gym,massage
number,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0
47,2,22,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN

## Correcting a false value

In [11]:
### In the next example the false age 47 is corrected from the row 47 of index column

df.loc[47, 'age'] = 42

### Let us check the result

df

,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties,occu_health,timeshare,gym,massage
number,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0
47,2,42,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN

## Calculating new variables

In [13]:
### In this example a new variable 'sex_string' is created and sexes are stored in it as text strings.
### Note the use od the data structure dictionary between {}

df['sex_string'] = df['sex'].replace({1 : 'Male', 2 : 'Female'})

### Finally, let's view the result. See the right-most column and compare the contents with the second column.

df

,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties,occu_health,timeshare,gym,massage,sex_string
number,,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN,Male
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN,Male
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN,Male
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN,Male
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN,Male
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN,Female
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN,Male
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN,Male
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN,Male
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN,Male
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN,Male
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0,Male
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN,Male
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN,Male
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0,Female
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN,Male
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN,Female
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0,Male
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0,Female
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN,Female
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN,Male
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN,Male
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0,Male
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0,Male
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0,Female
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN,Male
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN,Male
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0,Male
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN,Male
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN,Male
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0,Male
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0,Male
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN,Male
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0,Female
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN,Male
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN,Male
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN,Male
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN,Male
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN,Male
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Female
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0,Male
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0,Male
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0,Female
47,2,42,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN,Female
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN,Male
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN,Male
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN,Male
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN,Female
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN,Male
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN,Male
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN,Male
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0,Female
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0,Female
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0,Male
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0,Male
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN,Male
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN,Male
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN,Male
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN,Male
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN,Female
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0,Female
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0,Female
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN,Female
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0,Male
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN,Male
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN,Male
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0,Male
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN,Male
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN,Male
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN,Female
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN,Male
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN,Male
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN,Male
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN,Male
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN,Male
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN,Male
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN,Male
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN,Male
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN,Female

In [14]:
### In this example we define a new categorical variable for different age groups.

### First we specify class boundaries for age classes.

boundaries = [18, 28, 38, 48, 58, 68]

### Next we define a new variable 'age_group' in which ages are classified into age groups.

df['age_group'] = pd.cut(df['age'], bins = boundaries)

### See the resulting data.
### Here standard notation is used, e.g., (28,38] is the group of ages of which 28 is not included but 38 is included.

df

,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties,occu_health,timeshare,gym,massage,sex_string,age_group
number,,,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN,Male,"(28, 38]"
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN,Male,"(28, 38]"
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN,Male,"(18, 28]"
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN,Female,"(28, 38]"
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN,Male,"(48, 58]"
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN,Male,"(48, 58]"
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN,Male,"(38, 48]"
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN,Male,"(28, 38]"
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN,Male,"(38, 48]"
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0,Male,"(38, 48]"
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN,Male,"(28, 38]"
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN,Male,"(48, 58]"
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male,"(48, 58]"
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0,Female,"(38, 48]"
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN,Male,"(18, 28]"
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN,Female,"(28, 38]"
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0,Male,"(38, 48]"
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0,Female,"(38, 48]"
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN,Female,"(38, 48]"
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN,Male,"(38, 48]"
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male,"(38, 48]"
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN,Male,"(28, 38]"
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male,"(38, 48]"
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0,Male,"(18, 28]"
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0,Male,"(18, 28]"
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0,Female,"(48, 58]"
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN,Male,"(38, 48]"
30,1,21,1,NaN,NaN,1949,4,4.0,3,3,2,1.0,NaN,NaN,NaN,Male,"(18, 28]"
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0,Male,"(18, 28]"
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN,Male,"(38, 48]"
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN,Male,"(58, 68]"
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0,Male,"(28, 38]"
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0,Male,"(18, 28]"
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0,Female,"(48, 58]"
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN,Male,"(48, 58]"
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN,Male,"(28, 38]"
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN,Male,"(28, 38]"
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Female,"(38, 48]"
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0,Male,"(28, 38]"
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0,Male,"(48, 58]"
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0,Female,"(48, 58]"
47,2,42,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN,Female,"(38, 48]"
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN,Male,"(28, 38]"
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN,Male,"(18, 28]"
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN,Female,"(38, 48]"
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN,Male,"(38, 48]"
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN,Male,"(38, 48]"
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN,Male,"(18, 28]"
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0,Female,"(38, 48]"
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0,Female,"(28, 38]"
57,1,61,2,2.0,36.0,3119,2,NaN,2,1,5,1.0,NaN,NaN,1.0,Male,"(58, 68]"
58,1,38,2,2.0,NaN,2574,2,3.0,1,1,2,1.0,NaN,NaN,1.0,Male,"(28, 38]"
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN,Male,"(18, 28]"
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]"
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN,Male,"(38, 48]"
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN,Male,"(38, 48]"
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN,Female,"(48, 58]"
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0,Female,"(38, 48]"
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0,Female,"(28, 38]"
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN,Female,"(28, 38]"
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0,Male,"(28, 38]"
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN,Male,"(28, 38]"
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN,Male,"(18, 28]"
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0,Male,"(48, 58]"
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN,Male,"(28, 38]"
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN,Male,"(38, 48]"
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN,Female,"(38, 48]"
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN,Male,"(38, 48]"
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN,Male,"(38, 48]"
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN,Male,"(28, 38]"
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN,Male,"(38, 48]"
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN,Male,"(18, 28]"
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN,Male,"(28, 38]"
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN,Male,"(18, 28]"
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN,Male,"(28, 38]"
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN,Female,"(28, 38]"

In [16]:
### There are five different variables for satisfaction to different employment areas.
### Using these variables we next calculate overall satisfaction of respondents.

### In the next command the parameter 'axis = 1' means that the calculation is done by calculating the average of row.

df['satisfaction'] = df[['management', 'colleagues', 'environment', 'salary_level', 'duties']].mean(axis = 1)

### We then view results of satisfaction variables.

df[['management', 'colleagues', 'environment', 'salary_level', 'duties', 'satisfaction']]

,management,colleagues,environment,salary_level,duties,satisfaction
number,,,,,,
1,3,3.0,3,3,3,3.0
2,1,5.0,2,1,3,2.4
3,3,4.0,1,1,3,2.4
4,3,3.0,3,3,3,3.0
5,2,3.0,2,1,2,2.0
6,4,4.0,5,2,4,3.8
7,3,5.0,4,2,2,3.2
8,3,5.0,3,1,3,3.0
9,2,4.0,4,2,4,3.2
10,3,2.0,1,1,1,1.6
11,3,5.0,3,1,3,3.0
12,3,5.0,3,1,2,2.8
13,3,5.0,3,1,4,3.2
14,4,5.0,4,1,3,3.4
15,4,4.0,4,4,4,4.0
16,3,3.0,3,3,3,3.0
17,5,5.0,5,4,5,4.8
18,4,3.0,4,2,1,2.8
19,2,3.0,4,1,4,2.8
20,3,3.0,4,3,2,3.0
21,2,4.0,5,3,4,3.6
22,2,4.0,3,2,4,3.0
23,4,4.0,4,4,4,4.0
24,3,4.0,3,4,5,3.8
25,4,4.0,4,4,4,4.0
26,2,4.0,2,1,3,2.4
27,2,4.0,2,2,3,2.6
28,3,4.0,3,2,4,3.2
29,2,4.0,3,1,4,2.8
30,4,4.0,3,3,2,3.2
31,4,5.0,3,4,2,3.6
32,4,4.0,4,3,4,3.8
33,4,4.0,5,4,4,4.2
34,1,5.0,1,1,2,2.0
35,3,4.0,3,3,3,3.2
36,2,4.0,3,1,3,2.6
37,5,5.0,5,5,5,5.0
38,5,5.0,4,1,4,3.8
39,3,5.0,3,3,4,3.6
40,1,5.0,4,1,3,2.8
41,3,3.0,4,2,3,3.0
42,3,4.0,3,1,2,2.6
43,4,4.0,4,4,4,4.0
44,2,3.0,4,1,3,2.6
45,4,5.0,4,2,4,3.8
46,3,3.0,2,2,3,2.6
47,3,3.0,4,1,3,2.8
48,4,5.0,4,1,3,3.4
49,4,4.0,3,3,5,3.8
50,3,4.0,3,2,3,3.0
51,4,5.0,5,4,5,4.6
52,5,5.0,5,2,5,4.4
53,1,2.0,2,1,1,1.4
54,2,4.0,3,1,2,2.4
55,3,5.0,4,3,3,3.6
56,4,4.0,4,3,3,3.6
57,2,NaN,2,1,5,2.5
58,2,3.0,1,1,2,1.8
59,3,4.0,3,2,3,3.0
60,4,4.0,3,1,3,3.0
61,2,2.0,1,1,2,1.6
62,2,3.0,1,2,3,2.2
63,4,3.0,2,2,3,2.8
64,4,4.0,3,2,3,3.2
65,4,4.0,5,2,4,3.8
66,5,5.0,5,4,5,4.8
67,3,4.0,3,2,2,2.8
68,2,4.0,3,1,4,2.8
69,4,5.0,3,1,4,3.4
70,3,4.0,3,2,2,2.8
71,3,5.0,5,3,4,4.0
72,3,5.0,5,3,4,4.0
73,5,3.0,4,3,4,3.8
74,3,5.0,1,1,3,2.6
75,1,5.0,1,1,1,1.8
76,1,5.0,1,1,1,1.8
77,4,5.0,3,1,2,3.0
78,4,4.0,4,3,4,3.8
79,1,3.0,2,1,2,1.8
80,3,4.0,3,3,3,3.2
81,3,4.0,3,3,3,3.2
82,3,4.0,4,3,4,3.6

In [17]:
### In this example a new variable is defined and the numbers of used benefits is calculated.


df['benefits'] = df[['occu_health', 'timeshare', 'gym', 'massage']].count(axis = 1)

### Next view the detailed usage of benefits and the total of them for each employee.

df[['occu_health', 'timeshare', 'gym', 'massage', 'benefits']]

        occu_health  timeshare  gym  massage  benefits
number
1               NaN        NaN  NaN      NaN         0
2               NaN        NaN  NaN      NaN         0
3               1.0        NaN  NaN      NaN         1
4               1.0        NaN  NaN      NaN         1
5               1.0        NaN  NaN      NaN         1
6               1.0        1.0  NaN      NaN         2
7               NaN        NaN  1.0      NaN         1
8               1.0        NaN  NaN      NaN         1
9               NaN        1.0  NaN      NaN         1
10              1.0        NaN  NaN      NaN         1
11              NaN        NaN  NaN      NaN         0
12              NaN        1.0  NaN      1.0         2
13              NaN        1.0  NaN      NaN         1
14              NaN        NaN  NaN      NaN         0
15              NaN        1.0  NaN      NaN         1
16              1.0        NaN  NaN      1.0         2
17              NaN        NaN  1.0      NaN         1
18              NaN        NaN  NaN      NaN         0
19              1.0        NaN  NaN      1.0         2
20              1.0        NaN  NaN      1.0         2
21              NaN        NaN  NaN      NaN         0
22              NaN        1.0  NaN      NaN         1
23              NaN        1.0  NaN      NaN         1
24              NaN        NaN  NaN      NaN         0
25              NaN        1.0  NaN      NaN         1
26              1.0        NaN  1.0      1.0         3
27              1.0        NaN  NaN      1.0         2
28              1.0        NaN  NaN      1.0         2
29              1.0        NaN  NaN      NaN         1
30              1.0        NaN  NaN      NaN         1
31              1.0        NaN  1.0      1.0         3
32              NaN        1.0  NaN      NaN         1
33              NaN        1.0  NaN      NaN         1
34              1.0        NaN  NaN      1.0         2
35              1.0        NaN  1.0      1.0         3
36              1.0        NaN  NaN      NaN         1
37              NaN        NaN  NaN      1.0         1
38              1.0        1.0  NaN      NaN         2
39              NaN        NaN  NaN      NaN         0
40              1.0        NaN  NaN      NaN         1
41              1.0        NaN  NaN      NaN         1
42              1.0        NaN  NaN      NaN         1
43              NaN        1.0  NaN      NaN         1
44              1.0        NaN  NaN      1.0         2
45              1.0        NaN  NaN      1.0         2
46              1.0        NaN  NaN      1.0         2
47              NaN        NaN  1.0      NaN         1
48              NaN        NaN  NaN      NaN         0
49              NaN        NaN  1.0      NaN         1
50              1.0        NaN  NaN      NaN         1
51              NaN        1.0  NaN      NaN         1
52              NaN        1.0  NaN      NaN         1
53              1.0        NaN  NaN      NaN         1
54              1.0        NaN  NaN      NaN         1
55              NaN        NaN  NaN      1.0         1
56              1.0        NaN  NaN      1.0         2
57              1.0        NaN  NaN      1.0         2
58              1.0        NaN  NaN      1.0         2
59              NaN        NaN  NaN      NaN         0
60              1.0        NaN  NaN      NaN         1
61              1.0        NaN  NaN      NaN         1
62              1.0        NaN  NaN      NaN         1
63              1.0        NaN  NaN      NaN         1
64              1.0        NaN  NaN      1.0         2
65              1.0        NaN  NaN      1.0         2
66              1.0        1.0  NaN      NaN         2
67              1.0        1.0  NaN      1.0         3
68              NaN        NaN  NaN      NaN         0
69              NaN        NaN  NaN      NaN         0
70              1.0        1.0  NaN      1.0         3
71              NaN        1.0  NaN      NaN         1
72              NaN        1.0  NaN      NaN         1
73              1.0        NaN  NaN      NaN         1
74              1.0        NaN  NaN      NaN         1
75              1.0        NaN  NaN      NaN         1
76              1.0        NaN  NaN      NaN         1
77              NaN        NaN  NaN      NaN         0
78              NaN        1.0  1.0      NaN         2
79              1.0        NaN  NaN      NaN         1
80              1.0        NaN  1.0      NaN         2
81              NaN        NaN  NaN      NaN         0
82              1.0        NaN  NaN      NaN         1

In [19]:
### Next take a closure look at the types of variables we defined above.

### Notice that sex_string has type object and age_group has type catogory.

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 82 entries, 1 to 82
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sex           82 non-null     int64
 1   age           82 non-null     int64
 2   family        82 non-null     int64
 3   education     81 non-null     float64
 4   empl_years    80 non-null     float64
 5   salary        82 non-null     int64
 6   management    82 non-null     int64
 7   colleagues    81 non-null     float64
 8   environment   82 non-null     int64
 9   salary_level  82 non-null     int64
 10  duties        82 non-null     int64
 11  occu_health   47 non-null     float64
 12  timeshare     20 non-null     float64
 13  gym           9 non-null      float64
 14  massage       22 non-null     float64
 15  sex_string    82 non-null     object
 16  age_group     82 non-null     category
 17  satisfaction  82 non-null     float64
 18  benefits      82 non-null     int64
dtypes: category(1), float64(8), int64(9), object(1)
memory usage: 14.6+ KB

## Removing rows with missing values

In [20]:
### In this example we remove rows in which values for either education, empl_years or colleagues is missing

df2 = df.dropna(subset = ['education', 'empl_years', 'colleagues'])
df2

,sex,age,family,education,empl_years,salary,management,colleagues,environment,salary_level,duties,occu_health,timeshare,gym,massage,sex_string,age_group,satisfaction,benefits
number,,,,,,,,,,,,,,,,,,,
1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN,Male,"(28, 38]",3.0,0
2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN,Male,"(28, 38]",2.4,0
3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",2.4,1
4,1,36,2,1.0,14.0,2144,3,3.0,3,3,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",3.0,1
5,1,24,1,2.0,4.0,2183,2,3.0,2,1,2,1.0,NaN,NaN,NaN,Male,"(18, 28]",2.0,1
6,2,31,2,2.0,14.0,1910,4,4.0,5,2,4,1.0,1.0,NaN,NaN,Female,"(28, 38]",3.8,2
7,1,49,1,2.0,16.0,2066,3,5.0,4,2,2,NaN,NaN,1.0,NaN,Male,"(48, 58]",3.2,1
8,1,55,1,1.0,0.0,2066,3,5.0,3,1,3,1.0,NaN,NaN,NaN,Male,"(48, 58]",3.0,1
9,1,40,2,1.0,23.0,2768,2,4.0,4,2,4,NaN,1.0,NaN,NaN,Male,"(38, 48]",3.2,1
10,1,33,1,1.0,16.0,2106,3,2.0,1,1,1,1.0,NaN,NaN,NaN,Male,"(28, 38]",1.6,1
11,1,39,2,1.0,22.0,2651,3,5.0,3,1,3,NaN,NaN,NaN,NaN,Male,"(38, 48]",3.0,0
12,1,40,2,3.0,21.0,2846,3,5.0,3,1,2,NaN,1.0,NaN,1.0,Male,"(38, 48]",2.8,2
13,1,35,2,3.0,15.0,2808,3,5.0,3,1,4,NaN,1.0,NaN,NaN,Male,"(28, 38]",3.2,1
14,1,58,2,3.0,21.0,3587,4,5.0,4,1,3,NaN,NaN,NaN,NaN,Male,"(48, 58]",3.4,0
15,1,53,2,3.0,12.0,3393,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male,"(48, 58]",4.0,1
16,2,42,2,3.0,23.0,2691,3,3.0,3,3,3,1.0,NaN,NaN,1.0,Female,"(38, 48]",3.0,2
17,1,26,1,4.0,2.0,5225,5,5.0,5,4,5,NaN,NaN,1.0,NaN,Male,"(18, 28]",4.8,1
18,2,38,2,3.0,17.0,2729,4,3.0,4,2,1,NaN,NaN,NaN,NaN,Female,"(28, 38]",2.8,0
19,1,42,1,3.0,20.0,2925,2,3.0,4,1,4,1.0,NaN,NaN,1.0,Male,"(38, 48]",2.8,2
20,2,40,2,2.0,13.0,2457,3,3.0,4,3,2,1.0,NaN,NaN,1.0,Female,"(38, 48]",3.0,2
21,2,40,2,3.0,20.0,2691,2,4.0,5,3,4,NaN,NaN,NaN,NaN,Female,"(38, 48]",3.6,0
22,1,47,2,3.0,17.0,4874,2,4.0,3,2,4,NaN,1.0,NaN,NaN,Male,"(38, 48]",3.0,1
23,1,44,2,1.0,27.0,3510,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male,"(38, 48]",4.0,1
24,1,36,1,3.0,7.0,4446,3,4.0,3,4,5,NaN,NaN,NaN,NaN,Male,"(28, 38]",3.8,0
25,1,43,2,3.0,1.0,2925,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Male,"(38, 48]",4.0,1
26,1,26,1,2.0,3.0,1521,2,4.0,2,1,3,1.0,NaN,1.0,1.0,Male,"(18, 28]",2.4,3
27,1,26,1,2.0,2.0,1989,2,4.0,2,2,3,1.0,NaN,NaN,1.0,Male,"(18, 28]",2.6,2
28,2,56,1,1.0,15.0,2223,3,4.0,3,2,4,1.0,NaN,NaN,1.0,Female,"(48, 58]",3.2,2
29,1,47,2,2.0,23.0,2808,2,4.0,3,1,4,1.0,NaN,NaN,NaN,Male,"(38, 48]",2.8,1
31,1,21,1,3.0,1.0,2340,4,5.0,3,4,2,1.0,NaN,1.0,1.0,Male,"(18, 28]",3.6,3
32,1,45,2,1.0,24.0,2925,4,4.0,4,3,4,NaN,1.0,NaN,NaN,Male,"(38, 48]",3.8,1
33,1,59,2,3.0,15.0,6278,4,4.0,5,4,4,NaN,1.0,NaN,NaN,Male,"(58, 68]",4.2,1
34,1,37,2,1.0,14.0,2183,1,5.0,1,1,2,1.0,NaN,NaN,1.0,Male,"(28, 38]",2.0,2
35,1,28,2,2.0,5.0,1989,3,4.0,3,3,3,1.0,NaN,1.0,1.0,Male,"(18, 28]",3.2,3
36,1,31,2,3.0,0.0,1559,2,4.0,3,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",2.6,1
37,2,56,2,2.0,17.0,2729,5,5.0,5,5,5,NaN,NaN,NaN,1.0,Female,"(48, 58]",5.0,1
38,1,50,2,1.0,1.0,2027,5,5.0,4,1,4,1.0,1.0,NaN,NaN,Male,"(48, 58]",3.8,2
39,1,30,1,2.0,10.0,2300,3,5.0,3,3,4,NaN,NaN,NaN,NaN,Male,"(28, 38]",3.6,0
40,1,32,1,1.0,3.0,2106,1,5.0,4,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",2.8,1
41,1,33,2,3.0,9.0,2846,3,3.0,4,2,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",3.0,1
42,1,29,1,2.0,6.0,2534,3,4.0,3,1,2,1.0,NaN,NaN,NaN,Male,"(28, 38]",2.6,1
43,2,40,2,3.0,12.0,2144,4,4.0,4,4,4,NaN,1.0,NaN,NaN,Female,"(38, 48]",4.0,1
44,1,30,1,2.0,7.0,2223,2,3.0,4,1,3,1.0,NaN,NaN,1.0,Male,"(28, 38]",2.6,2
45,1,55,2,1.0,35.0,2651,4,5.0,4,2,4,1.0,NaN,NaN,1.0,Male,"(48, 58]",3.8,2
46,2,51,2,1.0,28.0,1989,3,3.0,2,2,3,1.0,NaN,NaN,1.0,Female,"(48, 58]",2.6,2
47,2,42,1,3.0,21.0,1872,3,3.0,4,1,3,NaN,NaN,1.0,NaN,Female,"(38, 48]",2.8,1
48,1,34,2,1.0,18.0,2183,4,5.0,4,1,3,NaN,NaN,NaN,NaN,Male,"(28, 38]",3.4,0
49,1,27,2,2.0,7.0,2729,4,4.0,3,3,5,NaN,NaN,1.0,NaN,Male,"(18, 28]",3.8,1
50,1,29,1,3.0,7.0,2340,3,4.0,3,2,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",3.0,1
51,2,39,2,2.0,10.0,2106,4,5.0,5,4,5,NaN,1.0,NaN,NaN,Female,"(38, 48]",4.6,1
52,1,41,2,1.0,18.0,2261,5,5.0,5,2,5,NaN,1.0,NaN,NaN,Male,"(38, 48]",4.4,1
53,1,44,2,1.0,3.0,1989,1,2.0,2,1,1,1.0,NaN,NaN,NaN,Male,"(38, 48]",1.4,1
54,1,25,1,2.0,1.0,1559,2,4.0,3,1,2,1.0,NaN,NaN,NaN,Male,"(18, 28]",2.4,1
55,2,45,2,1.0,17.0,2417,3,5.0,4,3,3,NaN,NaN,NaN,1.0,Female,"(38, 48]",3.6,1
56,2,31,2,1.0,6.0,1949,4,4.0,4,3,3,1.0,NaN,NaN,1.0,Female,"(28, 38]",3.6,2
59,1,20,1,2.0,1.0,2261,3,4.0,3,2,3,NaN,NaN,NaN,NaN,Male,"(18, 28]",3.0,0
60,1,31,1,1.0,10.0,2144,4,4.0,3,1,3,1.0,NaN,NaN,NaN,Male,"(28, 38]",3.0,1
61,1,44,1,1.0,19.0,2183,2,2.0,1,1,2,1.0,NaN,NaN,NaN,Male,"(38, 48]",1.6,1
62,1,40,2,1.0,0.0,1872,2,3.0,1,2,3,1.0,NaN,NaN,NaN,Male,"(38, 48]",2.2,1
63,2,51,2,2.0,10.0,1872,4,3.0,2,2,3,1.0,NaN,NaN,NaN,Female,"(48, 58]",2.8,1
64,2,44,1,2.0,1.0,1715,4,4.0,3,2,3,1.0,NaN,NaN,1.0,Female,"(38, 48]",3.2,2
65,2,35,2,2.0,17.0,2691,4,4.0,5,2,4,1.0,NaN,NaN,1.0,Female,"(28, 38]",3.8,2
66,2,37,2,1.0,16.0,2027,5,5.0,5,4,5,1.0,1.0,NaN,NaN,Female,"(28, 38]",4.8,2
67,1,37,2,4.0,8.0,5069,3,4.0,3,2,2,1.0,1.0,NaN,1.0,Male,"(28, 38]",2.8,3
68,1,33,2,3.0,7.0,2417,2,4.0,3,1,4,NaN,NaN,NaN,NaN,Male,"(28, 38]",2.8,0
69,1,28,2,2.0,1.0,3510,4,5.0,3,1,4,NaN,NaN,NaN,NaN,Male,"(18, 28]",3.4,0
70,1,52,2,2.0,22.0,3119,3,4.0,3,2,2,1.0,1.0,NaN,1.0,Male,"(48, 58]",2.8,3
71,1,34,2,2.0,1.0,2495,3,5.0,5,3,4,NaN,1.0,NaN,NaN,Male,"(28, 38]",4.0,1
72,1,46,2,2.0,23.0,3470,3,5.0,5,3,4,NaN,1.0,NaN,NaN,Male,"(38, 48]",4.0,1
73,2,40,2,3.0,2.0,2027,5,3.0,4,3,4,1.0,NaN,NaN,NaN,Female,"(38, 48]",3.8,1
74,1,45,2,1.0,20.0,2846,3,5.0,1,1,3,1.0,NaN,NaN,NaN,Male,"(38, 48]",2.6,1
75,1,40,1,1.0,1.0,1949,1,5.0,1,1,1,1.0,NaN,NaN,NaN,Male,"(38, 48]",1.8,1
76,1,37,1,2.0,15.0,1598,1,5.0,1,1,1,1.0,NaN,NaN,NaN,Male,"(28, 38]",1.8,1
77,1,39,1,2.0,22.0,2183,4,5.0,3,1,2,NaN,NaN,NaN,NaN,Male,"(38, 48]",3.0,0
78,1,22,1,3.0,0.0,1598,4,4.0,4,3,4,NaN,1.0,1.0,NaN,Male,"(18, 28]",3.8,2
79,1,33,1,1.0,2.0,1638,1,3.0,2,1,2,1.0,NaN,NaN,NaN,Male,"(28, 38]",1.8,1
80,1,27,1,2.0,7.0,2612,3,4.0,3,3,3,1.0,NaN,1.0,NaN,Male,"(18, 28]",3.2,2
81,1,35,2,2.0,16.0,2808,3,4.0,3,3,3,NaN,NaN,NaN,NaN,Male,"(28, 38]",3.2,0
82,2,35,2,3.0,15.0,2183,3,4.0,4,3,4,1.0,NaN,NaN,NaN,Female,"(28, 38]",3.6,1

In [21]:
### After that there are only 79 rows in tha date when roiginally there were 82 of them.

df2.shape

(79, 19)

In [23]:
### Finally, we save the changed data in the Excel file named 'changed_data1.xlsx'

df2.to_excel('changed_data1_en.xlsx')

Source and origin of inspiration:<br /> 
Aki Taanila: Data-analytiikka Pythonilla: <a href="https://tilastoapu.wordpress.com/python/">https://tilastoapu.wordpress.com/python/</a>